// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyqoogrbfkvvkldxoali.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cW9vZ3JiZmt2dmtsZHhvYWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTQwNDQsImV4cCI6MjA3MTgzMDA0NH0.Bj9EHBWDdGtl7LHJgJN2KhfGwHhW837rjHDDmdNuLXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});